In [2]:
import numpy as np

## Project 1 

In [8]:
# 1.	Create a 1D array of numbers from 0 to 9

x = np.arange(10)
print("Array from 0 to 9:")
print(x)


Array from 0 to 9:
[0 1 2 3 4 5 6 7 8 9]


In [9]:
# 2.	Convert a 1D array to a 2D array with 2 rows
x = np.arange(10)
new_x = x.reshape (2,5)
print("New Array from 0 to 9:")
print(new_x)

New Array from 0 to 9:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# 3.	Write a NumPy program to create an array of the integers from 30 to 70.
x = np.arange(30, 70)
print("Array from 30 to 70:")
print(x)

In [11]:
# 4.	Write a NumPy program to append values to the end of an array.

x = [15, 25, 35]
print("This is the Original array:")
print(x)

x = np.append(x, [[45, 55, 65], [75, 85, 95]])
print("\nAfter append values to the end of the array:")
print(x)

This is the Original array:
[15, 25, 35]

After append values to the end of the array:
[15 25 35 45 55 65 75 85 95]


## Project 1 Extension

In [14]:
#1.	Write a NumPy program to find the number of rows and columns of a given matrix.
m= np.arange(20).reshape((4, 5))
print("Original matrix:")
print(m)
print("\nNumber of rows and columns of the said matrix:")
print(m.shape)

Original matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Number of rows and columns of the said matrix:
(4, 5)


In [15]:
#2.	Write a NumPy program to create an array of all the even integers from 30 to 70.
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array)

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [18]:
#3.	Write a NumPy program to convert a list and tuple into arrays.

my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 6, 5, 4], [0, 1, 2, 3])
print("\nTuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[0 1 2 3 4 5 6 7 8 9]

Tuple to array: 
[[8 6 5 4]
 [0 1 2 3]]


In [20]:
#4.	Write a NumPy program to create a structured array from given student name, height, class and their data types.  

data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Randolf', 6, 52.5),('Paul', 5, 42.10), ('Peter', 5, 40.11)]

# Create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("\nSort by height")
print(np.sort(students, order='height')) 

Original array:
[(b'James', 5, 48.5 ) (b'Randolf', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Peter', 5, 40.11)]

Sort by height
[(b'Peter', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Randolf', 6, 52.5 )]


## Task 2: Mathematics

In [22]:
# 1.	Write a NumPy program to add, subtract, multiply, divide arguments elementwise.
print("Add:")
print(np.add(1.0, 6.0))
print("\nSubtract:")
print(np.subtract(9.0, 2.0))
print("\nMultiply:")
print(np.multiply(1.0, 8.0))
print("\nDivide:")
print(np.divide(15.0, 2.0))

Add:
7.0

Subtract:
7.0

Multiply:
8.0

Divide:
7.5


In [24]:
# 2.	Write a NumPy program to round elements of the array to the nearest integer.

x = np.array([0.81, 1.55, 1.74, 2.86, 4.55, 6.90, 9.07])
print("Original array:")
print(x)
x = np.rint(x)
print("\nRound elements of the array to the nearest integer:")
print(x)

Original array:
[0.81 1.55 1.74 2.86 4.55 6.9  9.07]

Round elements of the array to the nearest integer:
[1. 2. 2. 3. 5. 7. 9.]


In [28]:
# 3.	Write a NumPy program to get true division of the element-wise array inputs.

x = np.arange(25)
print("Original array:")
print(x)
print("\nDivision of the array inputs, element-wise:")
print(np.true_divide(x, 5))

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

Division of the array inputs, element-wise:
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8]


## ## Task 2: Mathematics Extension

In [30]:
# 1.	Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.

x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("\nSecond array:")
print(y)
z = np.dot(x, y)
print("\nThe product of the two arrays:")
print(z)

First array:
[[0.56203987 0.44586578 0.19978299]
 [0.58336625 0.81514288 0.9985518 ]
 [0.39372815 0.83976241 0.01902133]
 [0.31372904 0.64763756 0.64312654]
 [0.77780001 0.32581585 0.42906518]]

Second array:
[[0.95001857 0.96244879]
 [0.5625843  0.76621719]
 [0.10729093 0.00477054]]

The product of the two arrays:
[[0.80622031 0.8835177 ]
 [1.11993091 1.19080026]
 [0.84852702 1.02247432]
 [0.73140078 0.80124723]
 [0.96825813 1.00028525]]


In [31]:
# 2.	Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.

x = np.random.randn(1000)
print("The Average of the array elements:")
mean = x.mean()
print(mean)
print("\nThe Standard deviation of the array elements:")
std = x.std()
print(std)
print("\nThe Variance of the array elements:")
var = x.var()
print(var)

The Average of the array elements:
0.010523701741711177

The Standard deviation of the array elements:
1.0019855080799527

The Variance of the array elements:
1.003974958402241


In [32]:
# 3.	Write a NumPy program to calculate round, floor, ceiling, truncated and round (to the given number of decimals) of the input, elementwise of a given array.
x = np.array([2.1, 4.5, 6.5, 3.9, 4.1, 5.5, 7.9])
print("Original array: ")
print(x)
r1 = np.round(x)
r2 = np.floor(x)
r3 = np.ceil(x)
r4 = np.trunc(x)
r5 = [round(elem) for elem in x]

print("\naround:   ", r1)
print("floor:    ",r2)
print("ceil:     ",r3)
print("trunc:    ",r4)
print("round:    ",r5)

Original array: 
[2.1 4.5 6.5 3.9 4.1 5.5 7.9]

around:    [2. 4. 6. 4. 4. 6. 8.]
floor:     [2. 4. 6. 3. 4. 5. 7.]
ceil:      [3. 5. 7. 4. 5. 6. 8.]
trunc:     [2. 4. 6. 3. 4. 5. 7.]
round:     [2, 4, 6, 4, 4, 6, 8]


In [35]:
# 4.	Write a Python program to find the maximum and minimum value of 1D array.

a = np.arange(4).reshape((2,2))
print("Original flattened or 1D array:")
print(a)
print("\nThe Maximum value of the above flattened or 1D array:")
print(np.amax(a))
print("\nThe Minimum value of the above flattened or 1D array:")
print(np.amin(a))

Original flattened or 1D array:
[[0 1]
 [2 3]]

The Maximum value of the above flattened or 1D array:
3

The Minimum value of the above flattened or 1D array:
0


## Optional task: Connecting Python and SQL

In [4]:
# Using the example code to help you, connect SQL to Python and complete the following tasks. Use the NumPy library to complete the following calculations.

import mysql.connector #Used for connecting to SQL
import numpy as np

db_connection = mysql.connector.connect(

host="localhost", user="sqluser", passwd="password" , database="uni")   #connect to database